FROM rust:1.57 as builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --release --locked

FROM ubuntu:20.04
COPY --from=builder /usr/src/app/target/release/client /usr/local/bin/simple-bitcoin-client
ENTRYPOINT ["simple-bitcoin-client"]
