version: '3'
services:
  server1:
    image: simple-bitcoin/server:latest
    command:
      ["-l", "0.0.0.0:20011"]
    environment:
      RUST_LOG: debug

  client1:
    image: simple-bitcoin/client:latest
    command:
      ["-l", "0.0.0.0:20013", "-c", "server1:20011"]
    environment:
      RUST_LOG: debug
